title: "Curly Designer - UX/UI Interactive Designer & Illustrator"
copyright: "Curly Designer 2021"
google_analytics: UA-1970564-13
permalink: /:title:output_ext
excerpt_separator: <!--more-->
intro:
  words:
    - "Design&nbsp;Thinking."
    - "UX/UI&nbsp;Architecture."
    - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IxD&nbsp;Design."
    - "&nbsp;Illustrations."
    - "&nbsp;Human&nbsp;Behavior."
    - "&nbsp;Product&nbsp;Design."
    - "&nbsp;&nbsp;&nbsp;UX&nbsp;Research."
  title: "MA. Design | B. Design | User Experience | Human Behavior | UI | IxD"
assets:
  sources: 
    - assets/css
    - assets/images
    - assets/js
  digest: false
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - .asset-cache
  - .history
