title: "Curly Designer - UX Interactive Digital Designer & Illustrator"
copyright: "Curly Designer 2020"
google_analytics: 
permalink: /:title:output_ext
excerpt_separator: <!--more-->
intro:
  words:
    - "Design&nbsp;Thinking."
    - "&nbsp;Product&nbsp;Design."
    - "UI&nbsp;Architecture."
    - "&nbsp;&nbsp;&nbsp;IxD&nbsp;Design."
    - "&nbsp;Illustrations."
    - "&nbsp;Human&nbsp;Behavior."
    - "&nbsp;&nbsp;&nbsp;&nbsp;Research."
  title: "MA USER EXPERIENCE | HUMAN Behavior | UI | IxD | DESIGNER"
assets:
  sources: 
    - assets/css
    - assets/images
    - assets/js
  digest: false
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - .asset-cache
  - .history
