title: "Curly Designer - UX Interactive Digital Designer & Illustrator"
google_analytics: 
excerpt_separator: <!--more-->
assets:
  sources: 
    - assets/css
    - assets/images
    - assets/js
  digest: false
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - .asset-cache
  - .history
