title: "Curly Designer - UX/UI Interactive Designer & Illustrator"
copyright: "Curly Designer 2021"
google_analytics: UA-1970564-13
permalink: /:title:output_ext
excerpt_separator: <!--more-->
intro:

  words:
    - "&nbsp;Design&nbsp;Thinking."
    - "&nbsp;&nbsp;Data&nbsp;Visualization."
    - "&nbsp;UX/UI&nbsp;Design."
    - "Human-Centered&nbsp;Design."
    - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IxD&nbsp;Design."
    - "&nbsp;Illustrations."
    - "&nbsp;Product&nbsp;Design."

  title: "MA. Design | B. Design | Data Visualization | UX UI Human-Centered Design | IxD"
assets:
  sources: 
    - assets/css
    - assets/images
    - assets/js
  digest: false
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - .asset-cache
  - .history
